name: tests unitaires
on: [push]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
      - name: Install Pytest
        run: pip install pytest
      - name: Run tests
        run: pytest TP1/test.py
      - name: Display branch
        run: echo "Nom Branche:${{ github.ref }}"
      - name: Display repo
        run: echo "Nom repo:${{ github.repository }}"
      - name: Display OS
        run: echo "OS:${{ runner.os }}"
